# Generated by Django 3.1.1 on 2020-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201011_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='viewsnum',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
