# Generated by Django 3.1.1 on 2020-10-12 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201012_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
