# Generated by Django 3.1.1 on 2020-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201013_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(related_name='article_views', to='mainapp.Viewing'),
        ),
    ]
