# Generated by Django 3.1.1 on 2020-10-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='article',
            field=models.ManyToManyField(related_name='hashtag', to='mainapp.Article'),
        ),
    ]
